spring:
  datasource:
    url: jdbc:mysql://cdb-aykvutvs.bj.tencentcdb.com:10225/graduation_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: dfxmysql5
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8191